<a href="https://colab.research.google.com/github/sharvani1357/Audio2art/blob/main/Numpy(Tekworks).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np

Creating Arrays


In [4]:
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr=np.array(3)
print(arr_3d)
print(arr)

print(arr.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
0
1
2
3


Using built-in functions


In [12]:
#array of zeros
zeros=np.zeros((2,3))
print(zeros)

#array of ones
ones=np.ones((3,2))
print(ones)

#array of random values
random_arr=np.random.random((2,2))
print(random_arr)

#identity matrix
identity=np.identity(3)
id2=np.eye(2)
print(identity)
print(id2)

#array with a range of values
range_arr=np.arange(0,10,2)#start,stop,step
print(range_arr)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.65112938 0.87975615]
 [0.54611485 0.9952782 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[0 2 4 6 8]


Array Attributes

In [13]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("size:",arr.size)
print("Data Type:",arr.dtype)
print("no.of dimensions:",arr.ndim)

shape: (2, 3)
size: 6
Data Type: int64
no.of dimensions: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [15]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("no of dimensions:",temp_data.ndim)
updated_temp_data=np.array([[22,25,20],[24,26,23],[21,23,22]])
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye((3))
print(updated_temp_data)
print(sensor_error_flags)
print(greenhouse_identity)



[[22 25 20]
 [24 26 23]]
shape: (2, 3)
size: 6
data type: int64
no of dimensions: 2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Indexing and slicing

In [21]:
#indexing
arr=np.array([[1,2,3],[34,35,56]])
print(arr)
print(arr[0,1])
print(arr[1,-1])
print(arr[0,-1])

#slicing
print(arr[0:,])
print(arr[0:2,1:3])

[[ 1  2  3]
 [34 35 56]]
2
56
3
[[ 1  2  3]
 [34 35 56]]
[[ 2  3]
 [35 56]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [23]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("no of apples on wed:",(arr[0,2]))
print("oranges on sun:",(arr[1,-1]))
print("weekday shipments (Mon–Fri) for all fruits:",(arr[0:2,0:5]))
print("weekend shipments (Sat & Sun):",(arr[0:2,5:7]))
print("Apples from Wednesday to Saturday:",(arr[0:,2:6]))
shipments[0,5]=100
print(shipments)




no of apples on wed: 3
oranges on sun: 56
weekday shipments (Mon–Fri) for all fruits: [[ 1  2  3]
 [34 35 56]]
weekend shipments (Sat & Sun): []
Apples from Wednesday to Saturday: [[ 3]
 [56]]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


Array Operations

In [27]:
#Arthimetic
a=np.array([1,2,3])
b=np.array([4,5,6])

print("addition:",a+b)
print("mul",a*b)
print("scalar",a*2)
print("sub",a-b)
print("div",a/b)
print("floor div",a//b)
print("mod",a%b)

#matrix multiplication
mat1=np.array([[2,3],[5,6]])
mat2=np.array([[7,8],[9,6]])
result=np.dot(mat1,mat2)
print(result)


addition: [5 7 9]
mul [ 4 10 18]
scalar [2 4 6]
sub [-3 -3 -3]
div [0.25 0.4  0.5 ]
floor div [0 0 0]
mod [1 2 3]
[[41 34]
 [89 76]]


Broadcasting:
Numpy automatically applies operations across arrays of different shapes when compatible

In [28]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


Universal Functions(ufuncs)

1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [31]:
#Exponentiation
print(np.exp(arr))
#square root
print(np.sqrt(arr))
#logarith
print(np.log(arr))



[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.83461743e+14 1.58601345e+15 2.09165950e+24]]
[[1.         1.41421356 1.73205081]
 [5.83095189 5.91607978 7.48331477]]
[[0.         0.69314718 1.09861229]
 [3.52636052 3.55534806 4.02535169]]


Aggregation Functions


In [32]:
arr=np.array([1,2,3,4])
print("sum:",np.sum(arr))
print("mean:",np.mean(arr))
print("sd:",np.std(arr))
print("max:",np.max(arr))
print("min:",np.min(arr))

sum: 10
mean: 2.5
sd: 1.118033988749895
max: 4
min: 1


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [50]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
#   Stack into 3D array
production_all = np.array([farmA, farmB, farmC], dtype=float)

# 2 Array attributes
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("No. of dimensions:", production_all.ndim)

# 3.Per-farm totals & statistics
total_per_farm = np.sum(production_all, axis=(1,2))
mean_per_farm = np.mean(production_all, axis=(1,2))
std_overall = np.std(production_all)
var_overall = np.var(production_all)

print("\nTotal energy per farm:", total_per_farm)
print("Mean energy per farm:", mean_per_farm)
print("Overall std:", std_overall)
print("Overall var:", var_overall)

# 4.Weighted per-panel (matrix multiplication)
hour_weights = np.array([0.5,1.0,0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print("\nWeighted energy per panel (shape):", weighted_per_panel.shape)
print("First farm weighted:", weighted_per_panel[0])

# 5.Add 0.5 kWh to Farm B (broadcast)
production_all[1] += 0.5

# 6.Z-score normalization per farm
farm_means = np.mean(production_all, axis=(1,2), keepdims=True)
farm_stds = np.std(production_all, axis=(1,2), keepdims=True)
normalized = (production_all - farm_means)/farm_stds
print("\nNormalized shape:", normalized.shape)
print("First farm normalized first row:", normalized[0,0])

# 7.Exponential family ufuncs
exp_data = np.exp(normalized)
expm1_data = np.expm1(normalized)
safe_norm = normalized - np.min(normalized) + 1e-5
log_data = np.log(safe_norm)
log10_data = np.log10(safe_norm)
log2_data = np.log2(safe_norm)

print("\nExp first farm first row:", exp_data[0,0])
print("Log10 first farm first row:", log10_data[0,0])

# Trigonometric ufuncs
sin_data = np.sin(normalized)
cos_data = np.cos(normalized)
tan_data = np.tan(normalized)
clipped = np.clip(normalized, -1, 1)
arcsin_data = np.arcsin(clipped)
arccos_data = np.arccos(clipped)
arctan_data = np.arctan(normalized)
deg_data = np.degrees(normalized)
rad_data = np.radians(normalized)

print("\nSin first farm first row:", sin_data[0,0])
print("Arcsin first farm first row:", arcsin_data[0,0])

#  Rounding ufuncs
round_data = np.round(normalized)
floor_data = np.floor(normalized)
ceil_data = np.ceil(normalized)
trunc_data = np.trunc(normalized)
print("\nRounded first farm first row:", round_data[0,0])

# Comparison & logical ufuncs
high_output = production_all > 20
even_hours_mask = (production_all % 2 == 0)
and_mask = np.logical_and(high_output, even_hours_mask)
or_mask = np.logical_or(high_output, even_hours_mask)

print("\nHigh output mask first farm:", high_output[0])
print("Logical AND mask first farm:", and_mask[0])

# Bitwise ufuncs
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,1,0],[0,1,1],[1,0,0],[0,1,0]],
    [[0,1,1],[1,0,1],[1,1,0],[1,0,0]]
], dtype=np.int32)
bit_and = np.bitwise_and(alerts, production_all.astype(int))
bit_or = np.bitwise_or(alerts, production_all.astype(int))
bit_invert = np.invert(alerts)
print("\nBitwise AND first farm first row:", bit_and[0,0])

# Arithmetic ufuncs
add_data = np.add(production_all, 5)
sub_data = np.subtract(production_all, 5)
mul_data = np.multiply(production_all, 2)
div_data = np.divide(production_all, 2)
power_data = np.power(production_all, 2)
mod_data = np.mod(production_all, 3)

print("\nAdd first farm first row:", add_data[0,0])

# Aggregations over ufunc outputs
exp_sum = np.sum(np.exp(normalized))
sin_mean = np.mean(np.sin(normalized))
power_mean = np.mean(np.power(production_all, 2))
print("\nSum of exp(normalized):", exp_sum)
print("Mean of sin(normalized):", sin_mean)
print("Mean of production_all^2:", power_mean)

#  Broadcast-based summary table
panel_totals_per_farm = np.sum(production_all, axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("\nPanel totals per farm (first farm first row):", panel_totals_per_farm[0])
print("Needs maintenance per farm:", needs_maintenance)

#  Final KPIs
overall_total = np.sum(production_all)
peak_hour_value = np.max(production_all)
peak_index = np.argmax(production_all)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_index, production_all.shape)
average_per_panel = np.mean(production_all, axis=2)

print("\nOverall total energy:", overall_total)
print(f"Peak hour value: {peak_hour_value} (Farm {peak_farm}, Panel {peak_panel}, Hour {peak_hour})")
print("Average per panel across hours (first farm):", average_per_panel[0])











Shape: (3, 4, 3)
Size: 36
Dtype: float64
No. of dimensions: 3

Total energy per farm: [126. 234. 174.]
Mean energy per farm: [10.5 19.5 14.5]
Overall std: 4.179978734661485
Overall var: 17.472222222222225

Weighted energy per panel (shape): (3, 4)
First farm weighted: [25.25 23.   29.5  17.75]

Normalized shape: (3, 4, 3)
First farm normalized first row: [-0.25264558  0.75793673  0.25264558]

Exp first farm first row: [0.77674313 2.13386893 1.2874269 ]
Log10 first farm first row: [0.18066581 0.40251342 0.30560383]

Sin first farm first row: [-0.24996642  0.68742445  0.24996642]
Arcsin first farm first row: [-0.25541356  0.86014434  0.25541356]

Rounded first farm first row: [-0.  1.  0.]

High output mask first farm: [[False False False]
 [False False False]
 [False False False]
 [False False False]]
Logical AND mask first farm: [[False False False]
 [False False False]
 [False False False]
 [False False False]]

Bitwise AND first farm first row: [0 0 1]

Add first farm first row: [15.

Stacking and Splitting

In [49]:
a=np.array([1,2])
b=np.array([3,4])
#vertical stack
print(np.vstack((a,b)))
#horizontal stack
print(np.hstack((a,b)))

#splitting
arr=np.array([1,2,3,4,5,6])
#splitting into three parts
print(np.array_split(arr,3))


[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


Advanced Indexing

In [53]:
#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
#fancy indexing
arr=np.array([10,20,34,56])
indices=[0,2]
print(arr[indices])

[4 5]
[10 34]


Copy vs view

In [54]:
#view shares memory
arr=np.array([1,2,3])
view=arr.view()
view=arr.view()
view[0]=10
print(arr)

#copy does not share memory
copy=arr.copy()
copy[0]=10
print(arr)



[10  2  3]
[10  2  3]


Saving and Loading

In [56]:
#save a file
arr=np.array([1,2,3])
np.save('array.npy',arr)
#load from a file
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [88]:
arr=np.arange(10,51)
arr1=np.random.random((3,3))
print(arr)
print(arr1)
#1.Array Attributes
print(arr.shape)
print(arr.size)
print(arr.dtype)
#2.Basic opeartions
arr+=5
print(arr)
m1=np.array([[1,2,3],[5,6,7]])
m2=np.array([[4,6,5],[8,2,7]])
print(m1*m2)
#3.indexing and slicing
arr2=np.arange(1,26)
arr3=arr2.reshape(5,5)
print(arr3)
print(arr3[0,:])
print(arr3[:,-1])
print(arr3[0:3,0:2])
#4.Aggregation
arr4=np.random.randint(10,100,10)
print(arr4)
print(max(arr4))
print(min(arr4))
print(np.mean(arr4))
print(np.std(arr4))
#5.Reshaping
arr5=np.arange(1,13)
arr6=arr5.reshape(3,4)
print(arr6)
#6.Broadcasting
arr7=np.ones((3,3))
a=np.array([1,2,3])
print(arr7+a)
#7.filtering
arr8=np.random.randint(1,50,15)
arr8_f=arr8[arr8%5==0]
print(arr8_f)
#8.matrix multiplication
mat3=np.array([[1,2],[3,4]])
mat4=np.array([[5,6],[7,8]])
result=np.dot(mat3,mat4)
print(result)
#advanced indexing
arr9=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr9)
diagnols=arr9[np.arange(4),np.arange(4)]
print(diagnols)




[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.51470192 0.38080752 0.64167627]
 [0.34804622 0.03811027 0.58952629]
 [0.77220787 0.19779706 0.19948385]]
(41,)
41
int64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 4 12 15]
 [40 12 49]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
[77 88 94 60 11 47 12 89 68 42]
94
11
58.8
28.84024965217881
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[5]
[[19 22]
 [43 50]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
